### ISSUE TITLE
Bot token

### ISSUE THREAD

**Issue by ilcusu** [trenta3/telegrambot#1]
Forse dovresti evitare di tenere il token del bot direttamente sulla repository, altrimenti qualcuno potrebbe fregartelo.

**Comment by trenta3** [comment]
Molto giusto... Assolutamente da togliere
Il 24/set/2016 19:23 "Manuele Cusumano" notifications@github.com ha
scritto:

**Comment by trenta3** [comment]
Comunque sia il bot è stato cancellato da Telegram da un po'. Lo tolgo giusto per fare le cose per bene.
